name: lebonprix237
description: "Lebonprix 237 Manager - Gestion complète de l'entreprise"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # State management
  provider: ^6.1.1

  # Base de données locale
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1

  # PDF
  pdf: ^3.10.7
  printing: ^5.11.1

  # Médias / fichiers
  image_picker: ^1.0.7
  file_picker: ^8.1.2
  share_plus: ^10.1.2

  # Utilitaires
  intl: ^0.19.0
  url_launcher: ^6.2.4
  fl_chart: ^0.66.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
